### PR TITLE
add sail for developers

### PR DESCRIPTION
**Pull request by realpvz**
Add sail with :
- MySQL
- Redis
- Laravel

### CODE REVIEW

**Comment by muhammadmp97** [comment]
Thank you for your effort and contribution, but what's the point of using Sail instead of writing a straight dockerfile?

**Comment by realpvz** [comment]
It saves time and reduces the learning curve for contributors, making it easier for us to collaborate effectively. Allowing us to focus on the project, Its all about convenience and productivity, Next we can create our own Dockerfile for the production environment.

**Comment by realpvz** [comment]
> Thank you for your effort and contribution, but what's the point of using Sail instead of writing a straight dockerfile?


It saves time and reduces the learning curve for contributors, making it easier for us to collaborate effectively. Allowing us to focus on the project, Its all about convenience and productivity, Next we can create our own Dockerfile for the production environment.

**Comment by muhammadmp97** [comment]
I'll be doing this soon. @realpvz

**Pull request closed without merging**
